### ISSUE TITLE
[BUG] Update Interval in NSRule

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#253]

**Comment by fgalan** [comment]
I have done the following test on a Perse-FE 1.3.1 version (IoTP Partners envioronment) using the configuration portal (VR interface):

* 9:52: create a rule with two cards: entity type "test" + no signal with 60s and 11 min as checking interval, sending an email as result.
* 10:46: rule update to 17 min interval, all the other parameters the same
* 11:40: rule update to 19 min interval, all the other parameters the same
* 13:00: deleting the rule

The result is the following:

![imagen](https://user-images.githubusercontent.com/1534240/28872455-90999eca-7789-11e7-9639-cb8d62b19818.png)

It seems that each time the rule is updated a new timer is *added* instead of *modifying* the existing timer. At the end, after creation plus two updates, the rule has 3 timers at the same time (probably updating a third time before deleting will end in a fourth timer... although I haven't actually tested).

Deleting the rule seems to remove all timers (although I'm not sure if this a "complete clenaup" or the internal timer structure stills being dirty after deleting with some stale data).

Another (minor) fact in this test is the initial notification a 10:02. This is out of sync of the first time (the only one just after creating the rule), maybe it is a kind of creation-time glitch...

**Comment by fgalan** [comment]
A comparative comparison of 1.3.0 vs 1.5.0 code make us think that this could has been fixed in 1.5.0. Thus, the procedure above should be reproduced in 1.5.0 in order to see what's happen.

**Comment by mrutid** [comment]
What if...?
Maybe the problem, as Fermin said, is related with HA. Explore scenario with CEP A and CEP B, both sync via noSignal.refreshAllRules() (where rules are read from Mongo, then Added, and last Removed if they were not in mongo). 

In our case POST /rule could be processed by CEP A, PUT /rule could be processed by CEP B. Then when A syncs it reads and adds the modified Rule, with the new period. But never remove the timer because the rule is in both sets:

`  // remove old rules not in the new set
    deleteNSRuleIf(function(srv, subsrv, nm) {
        return !ruleSet.includes(srv, subsrv, nm);
    });`

Remarks: 

    DeleteNSRule is the only one in charge of remove timers. 
    Usual PUT/Modify performs always a DeleteRule prior to the AddRule.
    It could be simulated by inserting a modified Rule directly in mongo.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/255
